#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Lint et tests unitaires pour le front
npm --prefix ./wm-rajar-ms_writer/FRONT run lint && \
npm --prefix ./wm-rajar-ms_writer/FRONT run test && \

# Tests unitaires pour le back
npm --prefix ./wm-rajar-ms_writer/BACK run test:unit