name: Jobs CI

on: [push]

jobs:
  writer-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Front)
        run: npm install
        working-directory: wm-rajar-ms_writer/FRONT

      - name: Run ESLint
        run: npm run lint
        working-directory: wm-rajar-ms_writer/FRONT

      - name: Run Front unit tests
        run: npm run test
        working-directory: wm-rajar-ms_writer/FRONT
      
      - name: Install dependencies (Back)
        run: npm install
        working-directory: wm-rajar-ms_writer/BACK

      - name: Run BAck unit tests
        run: npm run test:unit
        working-directory: wm-rajar-ms_writer/BACK